on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          ssh-strict: false
          script: |
            cd /home/admin/github/mochuh-discord-bot/
            git pull
            screen -X -S mochuh quit
            sleep 5
            screen -dmS mochuh python3.9 mochuh.py
